# Configuración para Netlify
[build]
  # Directorio de publicación
  publish = "."
  
  # Comando de build (opcional, para sitios estáticos no es necesario)
  command = "echo 'Sitio estático - sin build necesario'"

# Configuración de headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; font-src 'self' fonts.googleapis.com fonts.gstatic.com; style-src 'self' 'unsafe-inline' fonts.googleapis.com; script-src 'self' 'unsafe-inline'; img-src 'self' data: https:; connect-src 'self' https:;"

# Configuración de caché
[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Redirects
[[redirects]]
  from = "/old-page"
  to = "/"
  status = 301

# Configuración de formularios (si los hay)
[[plugins]]
  package = "netlify-plugin-submit-sitemap"

# Configuración de optimización
[build.environment]
  NODE_VERSION = "18"

# Configuración de dominio personalizado
# Crear archivo CNAME con: pinturasbambi.com.py
